databases:
  - name: weedy-db
    databaseName: weedy_api_production
    plan: free

envVarGroups:
  - name: weedy-secrets
    envs:
      - key: RAILS_MASTER_KEY
        sync: false

services:
  - name: weedy-redis
    type: redis
    plan: free
    ipAllowList: []

  - name: weedy-api
    type: web
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0
      - fromGroup: weedy-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: weedy-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: weedy-redis
          property: connectionString

  - name: weedy-sidekiq
    type: worker
    plan: free
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec sidekiq"
    envVars:
      - key: RAILS_ENV
        value: production
      - fromGroup: weedy-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: weedy-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: weedy-redis
          property: connectionString
